import proposalImg from './images/pixar_proposal_finally_1789907355685.jpg';
import danceImg from './images/pixar_dance_wait_over_1789907371365.jpg';
import officialImg from './images/pixar_official_couple_1789907383557.jpg';
import marriedImg from './images/pixar_getting_married_1789907396161.jpg';
import invitationBgImg from './images/wedding_invitation_bg_1789907413037.jpg';

// Scene 3: Couple Attire Caricatures
import punjabiImg from './images/pixar_punjabi_couple_1789908154824.jpg';
import southImg from './images/pixar_south_couple_1789908169453.jpg';
import rajasthaniImg from './images/pixar_rajasthani_couple_1789908181087.jpg';
import bengaliImg from './images/pixar_bengali_couple_1789908200306.jpg';
import maharashtraImg from './images/pixar_maharashtra_couple_1789908234299.jpg';
import gujaratiImg from './images/pixar_gujarati_couple_1789908265875.jpg';
import kashmiriImg from './images/pixar_kashmiri_couple_1789908885454.jpg';
import keralaImg from './images/pixar_kerala_couple_1789908899211.jpg';
import beachImg from './images/pixar_beach_couple_1789908912504.jpg';
import awadhiImg from './images/pixar_awadhi_couple_1789908927586.jpg';
import assameseImg from './images/pixar_assamese_couple_1789908940996.jpg';

// Scene 1: State Proposals
import punjabiProposalImg from './images/pixar_punjabi_proposal_1789908518469.jpg';
import southProposalImg from './images/pixar_south_proposal_1789908534679.jpg';
import rajasthaniProposalImg from './images/pixar_rajasthani_proposal_1789908545732.jpg';
import maharashtraProposalImg from './images/pixar_maharashtra_proposal_1789908598939.jpg';
import gujaratiProposalImg from './images/pixar_gujarati_proposal_1789908613236.jpg';
import bengaliProposalImg from './images/pixar_bengali_proposal_1789908627298.jpg';
import kashmiriProposalImg from './images/pixar_kashmiri_proposal_1789908970518.jpg';
import keralaProposalImg from './images/pixar_kerala_proposal_1789908984359.jpg';
import beachProposalImg from './images/pixar_beach_proposal_1789909003386.jpg';
import awadhiProposalImg from './images/pixar_awadhi_proposal_1789909031397.jpg';

// Scene 2: Dedicated Celebration & Dance
import punjabiDanceImg from './images/pixar_punjabi_dance_1789909019986.jpg';
import garbaDanceImg from './images/pixar_garba_dance_1789908955533.jpg';
import rajasthaniDanceImg from './images/pixar_rajasthani_dance_1789910704880.jpg';

// Scene 4: Ornate Mandap & Wedding Cards
import punjabiWeddingCardImg from './images/pixar_punjabi_wedding_card_1789908559786.jpg';
import southWeddingCardImg from './images/pixar_south_wedding_card_1789908570938.jpg';

// User Uploaded & Sacred Wedding Rituals
import aarsiMirrorImg from './images/custom_aarsi_mirror.jpg';
import bridalEmbraceImg from './images/custom_bridal_embrace.jpg';
import intimateForeheadImg from './images/custom_intimate_forehead.jpg';
import sacredHastamelapImg from './images/custom_sacred_hastamelap.jpg';
import sindoorCeremonyImg from './images/user_sindoor_ceremony_1789917153399.jpg';
import kalireTriumphImg from './images/custom_kalire_triumph.jpg';

import { SceneItem, IndianStateTheme, IndianStateId, SceneryOption } from '../types';

export {
  proposalImg,
  danceImg,
  officialImg,
  marriedImg,
  invitationBgImg,
  punjabiImg,
  southImg,
  rajasthaniImg,
  bengaliImg,
  maharashtraImg,
  gujaratiImg,
  kashmiriImg,
  keralaImg,
  beachImg,
  awadhiImg,
  assameseImg,
  punjabiProposalImg,
  southProposalImg,
  rajasthaniProposalImg,
  maharashtraProposalImg,
  gujaratiProposalImg,
  bengaliProposalImg,
  kashmiriProposalImg,
  keralaProposalImg,
  beachProposalImg,
  awadhiProposalImg,
  punjabiDanceImg,
  garbaDanceImg,
  rajasthaniDanceImg,
  punjabiWeddingCardImg,
  southWeddingCardImg,
  aarsiMirrorImg,
  bridalEmbraceImg,
  intimateForeheadImg,
  sacredHastamelapImg,
  sindoorCeremonyImg,
  kalireTriumphImg,
};

export const INDIAN_STATE_THEMES: Record<IndianStateId, IndianStateTheme> = {
  bollywood: {
    id: 'bollywood',
    name: 'Pan-Indian / Bollywood Glam',
    stateLabel: 'Bollywood Glam',
    region: 'North & West',
    blessingHeader: '|| Shree Ganeshay Namah ||',
    defaultVenue: 'Hotel Ashriya International',
    defaultCity: 'Delhi / Mumbai',
    ceremonyType: 'Grand Wedding & Sangeet',
    musicTheme: 'romantic-waltz',
    brideAttire: 'Exquisite Magenta & Gold Embroidered Lehenga with Royal Kundan Choker',
    groomAttire: 'Regal Ivory & Gold Silk Sherwani with Brocade Stole',
    culturalVibe: 'Disney/Pixar Fairytale Romance, Wisteria Twilight, Sparkling Diamond Glow',
    officialCoupleImage: officialImg,
    accentColor: 'from-purple-500 to-pink-500',
    cardBorderColor: '#e9d5ff',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally...',
        subtitle: 'The Question of a Lifetime',
        actionText: 'He got down on one knee with all his heart',
        imageUrl: proposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Two Hearts Dancing as One',
        actionText: 'Lost in each other’s eyes under twilight blooms',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'A New Chapter Begins',
        actionText: 'Dressed in royal celebration and couture',
        imageUrl: officialImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Save Our Special Date',
        actionText: 'Join us to celebrate our forever love',
        imageUrl: marriedImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'bolly-proposal',
        label: 'Fairytale Diamond Proposal',
        category: 'proposal',
        imageUrl: proposalImg,
        description: 'Prince kneeling with sparkling solitaire ring beneath twilight sky',
      },
      {
        id: 'bolly-dance',
        label: 'Wisteria Ballroom Waltz',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Two hearts dancing as one under glowing purple wisteria blooms',
      },
      {
        id: 'bolly-attire',
        label: 'Royal Ivory & Rose Couture',
        category: 'attire',
        imageUrl: officialImg,
        description: 'Designer royal couple portrait in exquisite bridal couture',
      },
      {
        id: 'bolly-mandap',
        label: 'Fairytale Mandap Fireworks',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Royal fairytale wedding mandap with spectacular golden fireworks',
      },
      {
        id: 'bolly-arch',
        label: 'Opulent Palace Floral Arch',
        category: 'scenery',
        imageUrl: invitationBgImg,
        description: 'Carved golden palace archway adorned with marigolds and oil lanterns',
      },
    ],
  },

  punjab: {
    id: 'punjab',
    name: 'Punjab (Anand Karaj / Punjabi Wedding)',
    stateLabel: 'Punjab',
    region: 'North India',
    blessingHeader: '|| Lakh Khushian Patshahian • Ek Onkar ||',
    defaultVenue: 'The Grand Heritage Palace & Resorts',
    defaultCity: 'Amritsar / Chandigarh',
    ceremonyType: 'Anand Karaj & Grand Sangeet',
    musicTheme: 'festive-sangeet',
    brideAttire: 'Royal Crimson Red Bridal Lehenga, Red Choora Bangles, Golden Kalire & Maang Tikka',
    groomAttire: 'Ivory Embroidered Patiala Sherwani with Royal Red Turban (Pagri) & Pearl Kalgi',
    culturalVibe: 'Energetic Dhol Rhythms, Genda Phool Marigold Garlands, Royal Courtyard Lights',
    officialCoupleImage: punjabiImg,
    accentColor: 'from-amber-500 to-red-600',
    cardBorderColor: '#fca5a5',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Roka to Biah',
        subtitle: 'Munda got down on one knee with all his heart',
        actionText: 'And she said Haa! 💍 Dil Diyan Gallan',
        imageUrl: punjabiProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Nachde Ne Saare • Two Hearts, One Rhythm',
        actionText: 'Lost in the joyful beats of our eternal love ✨',
        imageUrl: punjabiDanceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Jodi Bani Rab Di • Anand Karaj',
        actionText: 'Patiala sherwani, red bridal lehenga & golden kalire',
        imageUrl: punjabiImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Lakh Khushian Patshahian • Save The Date',
        actionText: 'Bless our union under the holy Anand Karaj mandap',
        imageUrl: punjabiWeddingCardImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'punjab-proposal',
        label: 'Red Turban & Kalgi Proposal',
        category: 'proposal',
        imageUrl: punjabiProposalImg,
        description: 'Groom in red pagri with pearl kalgi proposing with diamond ring',
      },
      {
        id: 'punjab-dance',
        label: 'Sangeet Dhol Celebration Dance',
        category: 'dance',
        imageUrl: punjabiDanceImg,
        description: 'Joyful Punjabi couple dancing to lively dhol rhythms with festive confetti',
      },
      {
        id: 'punjab-attire',
        label: 'Patiala Sherwani & Kalire',
        category: 'attire',
        imageUrl: punjabiImg,
        description: 'Royal Patiala ivory sherwani, red bridal lehenga & golden kalire',
      },
      {
        id: 'punjab-mandap',
        label: 'Golden Anand Karaj Mandap',
        category: 'mandap',
        imageUrl: punjabiWeddingCardImg,
        description: 'Golden Anand Karaj mandap arch with Ek Onkar blessing',
      },
      {
        id: 'punjab-marigold',
        label: 'Royal Marigold Courtyard',
        category: 'scenery',
        imageUrl: invitationBgImg,
        description: 'Traditional Punjabi courtyard adorned with vibrant genda phool',
      },
      {
        id: 'punjab-bridal-embrace',
        label: 'Romantic Red Veil Embrace',
        category: 'ritual',
        imageUrl: bridalEmbraceImg,
        description: 'Intimate passionate hug with translucent red embroidered bridal dupatta & chooda',
      },
      {
        id: 'punjab-sindoor-ritual',
        label: 'Auspicious Sindoor Daan Ritual',
        category: 'ritual',
        imageUrl: sindoorCeremonyImg,
        description: 'Groom in royal sherwani and safa applying red vermillion to bride parting',
      },
    ],
  },

  rajasthan: {
    id: 'rajasthan',
    name: 'Rajasthan (Rajputana & Marwari Royal Vivah)',
    stateLabel: 'Rajasthan',
    region: 'West India',
    blessingHeader: '|| Shree Ganeshay Namah • Padharo Sa ||',
    defaultVenue: 'The Oberoi Udaivilas / City Palace',
    defaultCity: 'Udaipur / Jaipur',
    ceremonyType: 'Royal Rajputana Vivah',
    musicTheme: 'romantic-waltz',
    brideAttire: 'Magenta Pink & Gold Gota Patti Lehenga with Traditional Borla & Bridal Nath',
    groomAttire: 'Regal Cream Achkan Bandhgala with Saffron Royal Safa & Emerald Brooch',
    culturalVibe: 'Udaipur Lake Palace Balcony, Jharokhas, Lotus Water Fountains, Antique Gold Heritage',
    officialCoupleImage: rajasthaniImg,
    accentColor: 'from-amber-400 to-rose-600',
    cardBorderColor: '#fef08a',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Sajjan Re',
        subtitle: 'A Royal Palace Proposal Under The Stars',
        actionText: 'The Prince knelt with a solitaire diamond ring 💍',
        imageUrl: rajasthaniProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Padharo Mhare Des • Royal Palace Waltz',
        actionText: 'Dancing under jharokhas and glowing palace lanterns ✨',
        imageUrl: rajasthaniDanceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Royal Rajputana Vivah',
        actionText: 'Regal saffron safa, achkan & magenta gota patti lehenga',
        imageUrl: rajasthaniImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Shree Ganeshay Namah • Padharo Sa',
        actionText: 'Join us for a royal celebration of lifelong love',
        imageUrl: invitationBgImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'rajasthan-proposal',
        label: 'Udaipur Balcony Proposal',
        category: 'proposal',
        imageUrl: rajasthaniProposalImg,
        description: 'Rajput prince in saffron safa proposes on palace balcony with diamond ring',
      },
      {
        id: 'rajasthan-dance',
        label: 'Palace Jharokha Waltz',
        category: 'dance',
        imageUrl: rajasthaniDanceImg,
        description: 'Romantic royal waltz under palace jharokha with glowing fairy lights',
      },
      {
        id: 'rajasthan-attire',
        label: 'Regal Rajputana Portrait',
        category: 'attire',
        imageUrl: rajasthaniImg,
        description: 'Regal cream achkan, saffron safa & magenta gota patti lehenga',
      },
      {
        id: 'rajasthan-mandap',
        label: 'Carved Marble Mandap Arch',
        category: 'mandap',
        imageUrl: invitationBgImg,
        description: 'Ornate royal palace carved marble pillars and marigold garlands',
      },
      {
        id: 'rajasthan-fireworks',
        label: 'Palace Fireworks Vivah',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Royal palace mandap with sparkling fireworks in twilight sky',
      },
    ],
  },

  south: {
    id: 'south',
    name: 'South India (Tamil Nadu & Karnataka)',
    stateLabel: 'Tamil Nadu / Karnataka',
    region: 'South India',
    blessingHeader: '|| Om Sri Ganeshaya Namah • Subham Astu ||',
    defaultVenue: 'The Leela Palace / Traditional Mandapam',
    defaultCity: 'Chennai / Bengaluru',
    ceremonyType: 'Muhurtham & Kalyanam Ceremony',
    musicTheme: 'fairytale-ballad',
    brideAttire: 'Rich Crimson & Gold Kanjeevaram Silk Saree, Temple Gold Jewelry & White Jasmine Gajra',
    groomAttire: 'Traditional Raw Silk Veshti Mundu with Gold Zari Border & Angavastram',
    culturalVibe: 'Carved Temple Pillars, Glowing Brass Nilavilakku Lamps, Fragrant Malli Flowers',
    officialCoupleImage: southImg,
    accentColor: 'from-emerald-500 to-amber-500',
    cardBorderColor: '#86efac',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Kalyana Kanavu',
        subtitle: 'A Sacred Promise Under The Auspicious Dawn',
        actionText: 'He presented the glowing diamond ring... She said YES! 💍',
        imageUrl: southProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Sacred Melodies of Nadaswaram & Joy',
        actionText: 'Two souls united in divine temple harmony ✨',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Subha Muhurtham & Kalyanam',
        actionText: 'Pure Kanjeevaram silk, temple gold & gold zari veshti',
        imageUrl: southImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Om Sri Ganeshaya Namah • Subham Astu',
        actionText: 'Bless our sacred union surrounded by jasmine blossoms',
        imageUrl: southWeddingCardImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'south-proposal',
        label: 'Temple Courtyard Proposal',
        category: 'proposal',
        imageUrl: southProposalImg,
        description: 'Groom in raw silk veshti proposing with diamond ring in temple courtyard',
      },
      {
        id: 'south-dance',
        label: 'Sacred Temple Harmony Dance',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Romantic dance amidst glowing brass nilavilakku oil lamps and temple pillars',
      },
      {
        id: 'south-attire',
        label: 'Kanjeevaram Silk & Gold Zari',
        category: 'attire',
        imageUrl: southImg,
        description: 'Rich crimson Kanjeevaram silk saree, temple gold & gold zari veshti',
      },
      {
        id: 'south-mandap',
        label: 'Traditional Gopuram Mandapam',
        category: 'mandap',
        imageUrl: southWeddingCardImg,
        description: 'Carved temple mandapam with gopuram & brass deepams',
      },
      {
        id: 'south-floral',
        label: 'Jasmine & Marigold Mandap',
        category: 'scenery',
        imageUrl: invitationBgImg,
        description: 'Grand mandap framed with fragrant malli gajra and golden marigolds',
      },
    ],
  },

  kerala: {
    id: 'kerala',
    name: 'Kerala (Kasavu & Traditional Vivaham)',
    stateLabel: 'Kerala',
    region: 'South India',
    blessingHeader: '|| Om Sri Guruvayoorappan Prasadam • Subham ||',
    defaultVenue: 'Kumarakom Lake Resort / Guruvayur Mandapam',
    defaultCity: 'Kochi / Thrissur / Thiruvananthapuram',
    ceremonyType: 'Traditional Kerala Vivaham & Thali Kettu',
    musicTheme: 'fairytale-ballad',
    brideAttire: 'Off-White & Gold Zari Kasavu Silk Saree, Palakka Mala, Temple Jewelry & Fresh Jasmine',
    groomAttire: 'Pure White & Gold Kasavu Mundu with Golden Melmundu Border',
    culturalVibe: 'Brass Nilavilakku Lamps, Banana Stems, Fragrant Thulasi, Temple Lotus Pond',
    officialCoupleImage: keralaImg,
    accentColor: 'from-amber-300 to-emerald-600',
    cardBorderColor: '#fef08a',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Ente Pranayam',
        subtitle: 'A Sacred Promise At The Golden Hour',
        actionText: 'He held the diamond ring near the deepam... She said YES! 💍',
        imageUrl: keralaProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Sopana Sangeetham & Temple Harmonies',
        actionText: 'Our hearts intertwined amidst glowing golden oil lamps ✨',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Kerala Mangalya Vivaham',
        actionText: 'Pure Kasavu mundu, gold zari saree & palakka mala',
        imageUrl: keralaImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Om Sri Guruvayoorappan Prasadam • Subham',
        actionText: 'Bless our Thali Kettu ceremony and lifelong love',
        imageUrl: southWeddingCardImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'kerala-proposal',
        label: 'Temple Deepam Proposal',
        category: 'proposal',
        imageUrl: keralaProposalImg,
        description: 'Malayali groom in Kasavu mundu proposing by golden nilavilakku deepam',
      },
      {
        id: 'kerala-dance',
        label: 'Temple Courtyard Romance',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Romantic harmony dance amidst temple oil lamps and twilight garden',
      },
      {
        id: 'kerala-attire',
        label: 'Kasavu Mundu & Palakka Mala',
        category: 'attire',
        imageUrl: keralaImg,
        description: 'Off-white & gold Kasavu saree, Kasavu mundu & traditional palakka mala',
      },
      {
        id: 'kerala-mandap',
        label: 'Kerala Heritage Mandapam',
        category: 'mandap',
        imageUrl: southWeddingCardImg,
        description: 'Traditional Kerala temple mandap with brass nilavilakku and floral decor',
      },
      {
        id: 'kerala-marigold',
        label: 'Marigold Temple Arch',
        category: 'scenery',
        imageUrl: invitationBgImg,
        description: 'Auspicious temple arch decorated with traditional marigold garlands',
      },
    ],
  },

  maharashtra: {
    id: 'maharashtra',
    name: 'Maharashtra (Lagna / Peshwai Wedding)',
    stateLabel: 'Maharashtra',
    region: 'West India',
    blessingHeader: '|| Shubha Mangala Saavadhana ||',
    defaultVenue: 'Peshwa Durbar Heritage Lawns',
    defaultCity: 'Pune / Mumbai',
    ceremonyType: 'Maharashtrian Lagna Sohala',
    musicTheme: 'festive-sangeet',
    brideAttire: 'Bright Sunny Yellow & Green Nauvari Paithani Saree with Pearl Mundavalya & Crescent Bindi',
    groomAttire: 'Silk Dhoti Kurta with Royal Orange Pheta Turban & Pearl Mundavalya',
    culturalVibe: 'Peshwai Toran Mandap, Tutari Sound of Celebration, Traditional Marigold & Mango Leaves',
    officialCoupleImage: maharashtraImg,
    accentColor: 'from-amber-400 to-emerald-600',
    cardBorderColor: '#fde047',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Saakharpuda',
        subtitle: 'The Sweetest Promise of Forever',
        actionText: 'He knelt with pure love... and she said YES! 💍',
        imageUrl: maharashtraProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Jodi Kamal • Dhol-Tasha & Celebration',
        actionText: 'Dancing happily to the joyful rhythm of togetherness ✨',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Maharashtrian Lagna Sohala',
        actionText: 'Nauvari Paithani, orange pheta & pearl mundavalya',
        imageUrl: maharashtraImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Shubha Mangala Saavadhana',
        actionText: 'Bless our sacred union as we take the Saptapadi vows',
        imageUrl: invitationBgImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'maharashtra-proposal',
        label: 'Orange Pheta Proposal',
        category: 'proposal',
        imageUrl: maharashtraProposalImg,
        description: 'Groom in royal orange pheta proposing to bride in traditional attire',
      },
      {
        id: 'maharashtra-dance',
        label: 'Lagna Celebration Dance',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Couple celebrating and dancing happily to joyous wedding rhythms',
      },
      {
        id: 'maharashtra-attire',
        label: 'Nauvari Paithani & Pheta',
        category: 'attire',
        imageUrl: maharashtraImg,
        description: 'Yellow Nauvari Paithani saree, orange pheta & pearl mundavalya',
      },
      {
        id: 'maharashtra-mandap',
        label: 'Peshwai Toran Mandap Arch',
        category: 'mandap',
        imageUrl: invitationBgImg,
        description: 'Peshwai royal palace mandap arch decorated with marigold torans',
      },
      {
        id: 'maharashtra-celebration',
        label: 'Grand Lagna Fireworks',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Festive wedding mandap with golden fireworks celebration',
      },
    ],
  },

  bengal: {
    id: 'bengal',
    name: 'West Bengal (Shubho Bibaho)',
    stateLabel: 'West Bengal',
    region: 'East India',
    blessingHeader: '|| Shubho Bibaho • Shree Shree Prajapataye Namah ||',
    defaultVenue: 'ITC Royal Bengal / Heritage Rajbari',
    defaultCity: 'Kolkata',
    ceremonyType: 'Bengali Shubho Bibaho',
    musicTheme: 'celestial-piano',
    brideAttire: 'Glowing Red Banarasi Silk Saree, Intricate Sandalwood Chandan Facial Art & Traditional Mukut',
    groomAttire: 'Fine Ivory Tussar Silk Kurta, Dhoti with Traditional White Topor Headpiece',
    culturalVibe: 'Shubho Drishti Betel Leaf Ceremony, Conch Shell (Shankha) Sound, Terracotta Alpana',
    officialCoupleImage: bengaliImg,
    accentColor: 'from-red-500 to-rose-600',
    cardBorderColor: '#fecdd3',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Ashirbaad',
        subtitle: 'With All My Heart, Ogo Shuno',
        actionText: 'He asked the eternal question... and she said YES! 💍',
        imageUrl: bengaliProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Shubho Drishti • A Gaze Across Eternity',
        actionText: 'Our hearts beat as one to the sacred sound of Shankha ✨',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Bengali Shubho Bibaho',
        actionText: 'Red Banarasi, sandalwood chandan art, tussar silk & topor',
        imageUrl: bengaliImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Shubho Bibaho • Saat Paak & Sindoor Daan',
        actionText: 'Join our holy Saat Paak & sacred Sindoor Daan ritual',
        imageUrl: sindoorCeremonyImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'bengali-proposal',
        label: 'White Topor Ashirbaad Proposal',
        category: 'proposal',
        imageUrl: bengaliProposalImg,
        description: 'Bengali groom in white topor proposing with diamond ring',
      },
      {
        id: 'bengali-sindoor-daan',
        label: 'Sacred Sindoor Daan Ritual',
        category: 'ritual',
        imageUrl: sindoorCeremonyImg,
        description: 'Groom applying red vermillion to bride forehead parting',
      },
      {
        id: 'bengali-intimate-touch',
        label: 'Ashirbaad Forehead Touch',
        category: 'ritual',
        imageUrl: intimateForeheadImg,
        description: 'Romantic forehead to forehead touch with bridal red dupatta and ring',
      },
      {
        id: 'bengali-dance',
        label: 'Shubho Drishti Sacred Dance',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Romantic dance to the sacred sound of Shankha and twilight candles',
      },
      {
        id: 'bengali-attire',
        label: 'Red Banarasi & Chandan Art',
        category: 'attire',
        imageUrl: bengaliImg,
        description: 'Red Banarasi silk, sandalwood chandan art, tussar silk & white topor',
      },
      {
        id: 'bengali-mandap',
        label: 'Terracotta Alpana Rajbari Mandap',
        category: 'mandap',
        imageUrl: invitationBgImg,
        description: 'Terracotta Rajbari mandap arch with traditional alpana and marigolds',
      },
      {
        id: 'bengali-celebration',
        label: 'Royal Shubho Bibaho Celebration',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Grand heritage palace mandap illuminated with fireworks',
      },
    ],
  },

  gujarat: {
    id: 'gujarat',
    name: 'Gujarat (Lagna & Garba Celebration)',
    stateLabel: 'Gujarat',
    region: 'West India',
    blessingHeader: '|| Shree Ganeshay Namah • Jai Shree Krishna ||',
    defaultVenue: 'The Royal Green Mandap',
    defaultCity: 'Ahmedabad / Surat / Vadodara',
    ceremonyType: 'Gujarati Lagna & Sangeet',
    musicTheme: 'festive-sangeet',
    brideAttire: 'Red & White Panetar Gharchola Saree with Real Gold Zari & Kundan Jewels',
    groomAttire: 'Designer Raw Silk Achkan with Colorful Gujarati Bandhej Safa Turban',
    culturalVibe: 'Garba & Dandiya Festive Joy, Colorful Floral Torans, Auspicious Rangoli Art',
    officialCoupleImage: gujaratiImg,
    accentColor: 'from-rose-500 to-amber-500',
    cardBorderColor: '#fed7aa',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Sagai to Shubh Lagna',
        subtitle: 'Prem Ni Vaat • A Lifetime Promise',
        actionText: 'He presented the diamond ring... She said YES! 💍',
        imageUrl: gujaratiProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Raas Garba & Festive Melody',
        actionText: 'Dancing with golden dandiya to the melody of our love ✨',
        imageUrl: garbaDanceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Gujarati Shubh Lagna',
        actionText: 'Panetar Gharchola, gold zari & designer bandhej safa',
        imageUrl: gujaratiImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Jai Shree Krishna • Hastamelap',
        actionText: 'Bless our Mangal Pheras and lifelong journey together',
        imageUrl: marriedImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'gujarati-proposal',
        label: 'Bandhej Safa Sagai Proposal',
        category: 'proposal',
        imageUrl: gujaratiProposalImg,
        description: 'Groom in colorful bandhej safa proposing with diamond ring',
      },
      {
        id: 'gujarati-dance',
        label: 'Raas Garba Dandiya Dance',
        category: 'dance',
        imageUrl: garbaDanceImg,
        description: 'Couple dancing romantic Raas Garba with golden dandiya sticks',
      },
      {
        id: 'gujarati-attire',
        label: 'Panetar Gharchola & Bandhej Safa',
        category: 'attire',
        imageUrl: gujaratiImg,
        description: 'Red & white Panetar Gharchola, gold zari & designer bandhej safa',
      },
      {
        id: 'gujarati-mandap',
        label: 'Hastamelap Royal Mandap',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Royal wedding mandap with golden fireworks celebration',
      },
      {
        id: 'gujarati-floral',
        label: 'Floral Toran Mandap Arch',
        category: 'scenery',
        imageUrl: invitationBgImg,
        description: 'Festive mandap arch adorned with colorful marigold torans',
      },
    ],
  },

  kashmir: {
    id: 'kashmir',
    name: 'Kashmir & Pahadi (Himalayan Royal Vivah)',
    stateLabel: 'Kashmir / Pahadi',
    region: 'North (Himalayas)',
    blessingHeader: '|| Om Namah Shivaya • Subh Vivah ||',
    defaultVenue: 'The Lalit Grand Palace / Dal Lake Shikara',
    defaultCity: 'Srinagar / Jammu',
    ceremonyType: 'Kashmiri Pandit / Wazwan Royal Vivah',
    musicTheme: 'celestial-piano',
    brideAttire: 'Embroidered Ruby Velvet Pheran with Traditional Taranga & Gold Dejhoor Earrings',
    groomAttire: 'Ivory Pashmina Silk Achkan with Royal Kashmiri Brocade Shawl',
    culturalVibe: 'Snowy Himalayan Peaks, Dal Lake Shikaras, Pine Forests, Lotus Reflections',
    officialCoupleImage: kashmiriImg,
    accentColor: 'from-sky-400 to-rose-600',
    cardBorderColor: '#bae6fd',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Dal Lake Shikara',
        subtitle: 'A Fairytale Proposal Under Snowy Pines',
        actionText: 'He proposed on the floating Shikara... and she said YES! 💍',
        imageUrl: kashmiriProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Rabab & Santoor Melodies of the Valley',
        actionText: 'Lost in the magic of our first dance beneath snow-capped peaks ✨',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Kashmiri Royal Vivah',
        actionText: 'Velvet pheran, gold dejhoor & pashmina achkan',
        imageUrl: kashmiriImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Om Namah Shivaya • Subh Vivah',
        actionText: 'Join us amidst the mountain breezes to celebrate our union',
        imageUrl: invitationBgImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'kashmiri-proposal',
        label: 'Dal Lake Floating Shikara Proposal',
        category: 'proposal',
        imageUrl: kashmiriProposalImg,
        description: 'Groom proposing on floating Dal Lake Shikara under snowy Himalayan pines',
      },
      {
        id: 'kashmiri-dance',
        label: 'Himalayan Valley Waltz',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Romantic dance beneath snow-capped Himalayan peaks and pine breezes',
      },
      {
        id: 'kashmiri-attire',
        label: 'Ruby Velvet Pheran & Taranga',
        category: 'attire',
        imageUrl: kashmiriImg,
        description: 'Embroidered ruby velvet pheran, traditional Taranga & gold Dejhoor',
      },
      {
        id: 'kashmiri-mandap',
        label: 'Royal Himalayan Pine Mandap',
        category: 'mandap',
        imageUrl: invitationBgImg,
        description: 'Himalayan royal palace mandap arch framed with marigolds and pine',
      },
      {
        id: 'kashmiri-fireworks',
        label: 'Valley Twilight Celebration',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Fairytale mountain mandap with sparkling fireworks',
      },
    ],
  },

  awadh: {
    id: 'awadh',
    name: 'Awadh & Varanasi (Nawabi & Banarasi Vivah)',
    stateLabel: 'Awadh / Varanasi',
    region: 'Central / North',
    blessingHeader: '|| Har Har Mahadev • Sita Ram Kalyanam ||',
    defaultVenue: 'Brijrama Palace / Taj Falaknuma Lawns',
    defaultCity: 'Varanasi / Lucknow',
    ceremonyType: 'Awadhi Nawabi & Banarasi Vivah',
    musicTheme: 'romantic-waltz',
    brideAttire: 'Rich Crimson Varanasi Banarasi Silk Lehenga with Royal Side Passa & Diamond Nath',
    groomAttire: 'Lucknowi Zardozi Brocade Sherwani with Royal Feather Kalgi & Pearls',
    culturalVibe: 'Illuminated Ganga Ghats, Floating Evening Diyas, Grand Carved Nawabi Arches',
    officialCoupleImage: awadhiImg,
    accentColor: 'from-amber-500 to-red-600',
    cardBorderColor: '#fed7aa',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Ganga Ghats',
        subtitle: 'A Sacred Promise Over River Twilight',
        actionText: 'He asked for her hand amidst glowing evening diyas... YES! 💍',
        imageUrl: awadhiProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Aarsi Mushaf • Two Souls in the Mirror',
        actionText: 'Looking together into the sacred ornate mirror with eternal love ✨',
        imageUrl: aarsiMirrorImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Banarasi Vivah & Nawabi Shaan',
        actionText: 'Varanasi Banarasi silk, royal passa & Lucknowi brocade',
        imageUrl: awadhiImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Har Har Mahadev • Sita Ram Kalyanam',
        actionText: 'Bless our sacred wedding beside the holy Ganga waters',
        imageUrl: invitationBgImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'awadhi-proposal',
        label: 'Ganga Ghat Terrace Proposal',
        category: 'proposal',
        imageUrl: awadhiProposalImg,
        description: 'Groom proposing on palace terrace overlooking holy Ganga at twilight',
      },
      {
        id: 'awadhi-aarsi-mirror',
        label: 'Aarsi Mushaf Mirror Ceremony',
        category: 'ritual',
        imageUrl: aarsiMirrorImg,
        description: 'Bride and groom under ivory dupatta looking into ornate mirror',
      },
      {
        id: 'awadhi-dance',
        label: 'Nawabi Palace Terrace Dance',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Dancing under carved Nawabi arches and golden evening lanterns',
      },
      {
        id: 'awadhi-attire',
        label: 'Varanasi Banarasi & Lucknowi Brocade',
        category: 'attire',
        imageUrl: awadhiImg,
        description: 'Varanasi Banarasi silk lehenga, royal side passa & Lucknowi brocade',
      },
      {
        id: 'awadhi-mandap',
        label: 'Illuminated Ganga Ghat Mandap',
        category: 'mandap',
        imageUrl: invitationBgImg,
        description: 'Carved Nawabi palace mandap arch illuminated by floating evening diyas',
      },
      {
        id: 'awadhi-celebration',
        label: 'Grand Nawabi Fireworks',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Royal palace mandap with golden fireworks celebration',
      },
    ],
  },

  assam: {
    id: 'assam',
    name: 'Assam & North East (Traditional Assamese Biya)',
    stateLabel: 'Assam / North East',
    region: 'North East',
    blessingHeader: '|| Joy Aai Asom • Mangal Subha Vivah ||',
    defaultVenue: 'Kaziranga Heritage Resort & Lawns',
    defaultCity: 'Guwahati / Jorhat',
    ceremonyType: 'Traditional Assamese Biya (Joron & Biya)',
    musicTheme: 'celestial-piano',
    brideAttire: 'Radiant Golden Muga Silk Mekhela Chador with Red Kingkhap Motifs & Kopou Orchids',
    groomAttire: 'Ivory Muga Silk Dhoti Kurta with Traditional Red Embroidered Phulam Gamosa',
    culturalVibe: 'Lush Green Tea Gardens, Brahmaputra Twilight, Fragrant Kopou Orchids, Pepa Symphony',
    officialCoupleImage: assameseImg,
    accentColor: 'from-amber-400 to-emerald-600',
    cardBorderColor: '#fef08a',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Kopou Phool',
        subtitle: 'A Golden Promise Amongst Lush Tea Gardens',
        actionText: 'With orchids in the air, he held out the ring... YES! 💍',
        imageUrl: proposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Pepa & Dhol Romantic Symphony',
        actionText: 'Two souls dancing to the sweet melody of Brahmaputra breezes ✨',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Assamese Mangal Biya',
        actionText: 'Golden Muga silk Mekhela Chador & red Phulam Gamosa',
        imageUrl: assameseImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Joy Aai Asom • Mangal Subha Vivah',
        actionText: 'Join our Joron and Biya celebrations with warm blessings',
        imageUrl: invitationBgImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'assam-proposal',
        label: 'Tea Gardens & Orchids Proposal',
        category: 'proposal',
        imageUrl: proposalImg,
        description: 'A golden promise among lush tea gardens and fragrant kopou orchids',
      },
      {
        id: 'assam-dance',
        label: 'Pepa & Dhol Symphony Dance',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Dancing to the sweet melody of Brahmaputra breezes and festive rhythm',
      },
      {
        id: 'assam-attire',
        label: 'Golden Muga Silk & Gamosa',
        category: 'attire',
        imageUrl: assameseImg,
        description: 'Radiant golden Muga silk Mekhela Chador & red embroidered Phulam Gamosa',
      },
      {
        id: 'assam-mandap',
        label: 'Heritage Floral Mandap Arch',
        category: 'mandap',
        imageUrl: invitationBgImg,
        description: 'Traditional North East heritage floral mandap with marigold torans',
      },
      {
        id: 'assam-celebration',
        label: 'Grand Festive Biya Celebration',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Festive wedding mandap with sparkling golden fireworks',
      },
    ],
  },

  beach: {
    id: 'beach',
    name: 'Destination Beach (Goa Sunset Wedding)',
    stateLabel: 'Destination Beach / Goa',
    region: 'Coastal West',
    blessingHeader: '|| Forever & Always • Two Souls, One Ocean ||',
    defaultVenue: 'Taj Exotica / W Goa Beachfront Lawns',
    defaultCity: 'Goa / Alibaug',
    ceremonyType: 'Sunset Beachfront Vivah & Sundowner',
    musicTheme: 'fairytale-ballad',
    brideAttire: 'Flowing Peach & Champagne Shimmer Bridal Lehenga with Bohemian Floral Tiara',
    groomAttire: 'Tailored Pastel Blush Linen Sherwani with Golden Boutonniere',
    culturalVibe: 'Golden Sunset Ocean Waves, Floral Driftwood Canopy, Sea Breeze Fairy Lights',
    officialCoupleImage: beachImg,
    accentColor: 'from-teal-400 to-rose-400',
    cardBorderColor: '#99f6e4',
    scenes: [
      {
        id: 1,
        tag: 'scene1',
        title: 'Finally... Sunset On The Sand',
        subtitle: 'A Heart Carved in Rose Petals',
        actionText: 'He knelt on the golden sand... and she said YES! 💍',
        imageUrl: beachProposalImg,
        duration: 5.5,
        soundEffect: 'ring-chime',
      },
      {
        id: 2,
        tag: 'scene2',
        title: 'The Wait is Over',
        subtitle: 'Dancing Under Fairy Lit Driftwood',
        actionText: 'Lost in love as golden ocean waves crash softly ✨',
        imageUrl: danceImg,
        duration: 5.0,
        soundEffect: 'gentle-swell',
      },
      {
        id: 3,
        tag: 'scene3',
        title: 'We Are Making It Official',
        subtitle: 'Coastal Sunset Vivah',
        actionText: 'Pastel blush linen sherwani & peach shimmer lehenga',
        imageUrl: beachImg,
        duration: 5.0,
        soundEffect: 'harp-gliss',
      },
      {
        id: 4,
        tag: 'scene4',
        title: 'We Are Getting Married!',
        subtitle: 'Two Souls, One Ocean • Save Our Date',
        actionText: 'Join our barefoot sunset wedding celebration in paradise',
        imageUrl: invitationBgImg,
        duration: 6.5,
        soundEffect: 'wedding-fanfare',
      },
    ],
    sceneryOptions: [
      {
        id: 'beach-proposal',
        label: 'Sunset Beach Sand Proposal',
        category: 'proposal',
        imageUrl: beachProposalImg,
        description: 'Groom in linen kneeling on sunset beach sand with heart of rose petals',
      },
      {
        id: 'beach-dance',
        label: 'Barefoot Driftwood Sunset Dance',
        category: 'dance',
        imageUrl: danceImg,
        description: 'Dancing barefoot under fairy-lit driftwood with golden ocean breeze',
      },
      {
        id: 'beach-attire',
        label: 'Blush Linen & Peach Lehenga',
        category: 'attire',
        imageUrl: beachImg,
        description: 'Pastel blush linen sherwani & peach shimmer bridal lehenga',
      },
      {
        id: 'beach-mandap',
        label: 'Sunset Beach Canopy Mandap',
        category: 'mandap',
        imageUrl: invitationBgImg,
        description: 'Beachfront floral driftwood canopy mandap overlooking sunset waves',
      },
      {
        id: 'beach-celebration',
        label: 'Ocean Twilight Fireworks',
        category: 'mandap',
        imageUrl: marriedImg,
        description: 'Beachfront mandap with glittering fireworks over the ocean',
      },
    ],
  },
};

// The 4 Specific User Uploaded Images (Available across all 4 scene galleries)
export const USER_UPLOADED_FOUR_HERO_SCENES: SceneryOption[] = [
  {
    id: 'user-hero-kalire-hug',
    label: '👑 1. Golden Kalire Bridal Neck Hug',
    category: 'ritual',
    imageUrl: bridalEmbraceImg,
    description: 'Radiant bride hugging groom around neck with dangling golden kalire and cream pleated safa',
    themeName: 'User Uploaded 1',
  },
  {
    id: 'user-hero-forehead-touch',
    label: '👑 2. Forehead to Forehead Jaimala Touch',
    category: 'ritual',
    imageUrl: intimateForeheadImg,
    description: 'Intimate forehead touch with white pearl kalgi safa, red dupatta and rose jaimalas',
    themeName: 'User Uploaded 2',
  },
  {
    id: 'user-hero-hastamelap-hands',
    label: '👑 3. Sacred Hastamelap & Kanyadaan Hands',
    category: 'ritual',
    imageUrl: sacredHastamelapImg,
    description: 'Sacred hands holding with intricate bridal mehndi, flower diamond ring and holy mauli thread',
    themeName: 'User Uploaded 3',
  },
  {
    id: 'user-hero-aarsi-mirror',
    label: '👑 4. Aarsi Mushaf Mirror Reflection',
    category: 'ritual',
    imageUrl: aarsiMirrorImg,
    description: 'Bride and groom under ivory veil looking down into ornate gold mirror',
    themeName: 'User Uploaded 4',
  },
];

export const DEFAULT_SCENES: SceneItem[] = [
  {
    id: 1,
    tag: 'scene1',
    title: 'Finally...',
    subtitle: 'Golden Kalire Bridal Hug',
    actionText: 'Wrapped in warmth and dangling golden kalire',
    imageUrl: bridalEmbraceImg,
    duration: 5.5,
    soundEffect: 'ring-chime',
  },
  {
    id: 2,
    tag: 'scene2',
    title: 'The Wait is Over',
    subtitle: 'Forehead to Forehead Jaimala Touch',
    actionText: 'Two souls meeting under golden chandeliers and rose garlands',
    imageUrl: intimateForeheadImg,
    duration: 5.0,
    soundEffect: 'gentle-swell',
  },
  {
    id: 3,
    tag: 'scene3',
    title: 'We Are Making It Official',
    subtitle: 'Sacred Hastamelap Hands',
    actionText: 'Eternal vows bound with sacred thread and loving devotion',
    imageUrl: sacredHastamelapImg,
    duration: 5.0,
    soundEffect: 'harp-gliss',
  },
  {
    id: 4,
    tag: 'scene4',
    title: 'We Are Getting Married!',
    subtitle: 'Aarsi Mushaf Mirror Reflection',
    actionText: 'Reflecting pure love together beneath the sacred veil',
    imageUrl: aarsiMirrorImg,
    duration: 6.5,
    soundEffect: 'wedding-fanfare',
  },
];

// 18 Uploaded and Signature Indian Wedding Ritual & Ceremony Scenes
export const ALL_UPLOADED_AND_SACRED_SCENES: SceneryOption[] = [
  ...USER_UPLOADED_FOUR_HERO_SCENES,
  {
    id: 'user-hero-kalire-triumph',
    label: '📸 Uploaded: Hands Raised Kalire Celebration',
    category: 'dance',
    imageUrl: kalireTriumphImg,
    description: 'Joyful wedding couple raising joined hands high in celebration with golden kalire',
    themeName: 'Celebration Vivah',
  },
  {
    id: 'user-sindoor-ceremony',
    label: '📸 Uploaded: Sacred Sindoor Daan Ritual',
    category: 'ritual',
    imageUrl: sindoorCeremonyImg,
    description: 'Groom in royal sherwani and safa applying red vermillion to bride forehead parting',
    themeName: 'Sacred Vivah Sanskar',
  },
  {
    id: 'user-kerala-lift',
    label: '📸 Uploaded: South Kasavu Romantic Lift',
    category: 'attire',
    imageUrl: keralaImg,
    description: 'Groom in gold border veshti holding bride in cream Kasavu silk saree with jasmine',
    themeName: 'Kerala / South India',
  },
  {
    id: 'user-temple-deepam',
    label: '📸 Uploaded: Sacred Temple Gopuram Sanctum',
    category: 'mandap',
    imageUrl: keralaProposalImg,
    description: 'Carved stone temple pillars, glowing brass nilavilakku deepams & lotus pond',
    themeName: 'South India',
  },
  {
    id: 'user-regal-portrait',
    label: '📸 Uploaded: Regal Safa, Kalgi & Kundan',
    category: 'attire',
    imageUrl: rajasthaniImg,
    description: 'Royal Rajput couple in gold safa turban, kalgi brooch and magenta gota lehenga',
    themeName: 'Rajasthan',
  },
  {
    id: 'user-sangeet-dhol',
    label: '📸 Uploaded: Sangeet Dhol Celebration Dance',
    category: 'dance',
    imageUrl: punjabiDanceImg,
    description: 'Joyful Punjabi couple dancing to lively dhol beats with festive confetti',
    themeName: 'Punjab / Sangeet',
  },
  {
    id: 'user-garba-dance',
    label: '📸 Uploaded: Garba & Dandiya Festive Dance',
    category: 'dance',
    imageUrl: garbaDanceImg,
    description: 'Vibrant dandiya & garba celebration in mirrored Gujarati chaniya choli',
    themeName: 'Gujarat',
  },
  {
    id: 'user-ghoomar-dance',
    label: '📸 Uploaded: Ghoomar Royal Court Dance',
    category: 'dance',
    imageUrl: rajasthaniDanceImg,
    description: 'Royal palace courtyard dance under illuminated chandeliers and candle diyas',
    themeName: 'Rajasthan',
  },
  {
    id: 'user-ballroom-waltz',
    label: '📸 Uploaded: Fairytale First Dance Waltz',
    category: 'dance',
    imageUrl: danceImg,
    description: 'Two hearts dancing under glowing purple wisteria and fairy lights',
    themeName: 'Bollywood / Reception',
  },
  {
    id: 'user-mandap-fireworks',
    label: '📸 Uploaded: Sacred Mandap & Fireworks',
    category: 'mandap',
    imageUrl: marriedImg,
    description: 'Ornate royal wedding mandap with spectacular golden fireworks',
    themeName: 'Grand Vivah',
  },
  {
    id: 'user-awadhi-romance',
    label: '📸 Uploaded: Awadhi Royal Pastel Romance',
    category: 'attire',
    imageUrl: awadhiImg,
    description: 'Royal pastel lehenga, pearl side passa and Nawabi brocade sherwani',
    themeName: 'Awadh',
  },
  {
    id: 'user-awadhi-proposal',
    label: '📸 Uploaded: Awadhi Palace Proposal',
    category: 'proposal',
    imageUrl: awadhiProposalImg,
    description: 'Groom proposing with diamond ring overlooking royal courtyard',
    themeName: 'Awadh',
  },
  {
    id: 'user-beach-romance',
    label: '📸 Uploaded: Coastal Sunset Romance',
    category: 'attire',
    imageUrl: beachImg,
    description: 'Romantic couple on golden sand beach with palm trees at sunset',
    themeName: 'Goan Beach',
  },
  {
    id: 'user-fairytale-proposal',
    label: '📸 Uploaded: Classic Solitaire Proposal',
    category: 'proposal',
    imageUrl: proposalImg,
    description: 'Prince kneeling with sparkling diamond ring under magical twilight',
    themeName: 'Bollywood / Proposal',
  },
];

// Full catalog of all curated scenery options across all themes
export const ALL_CURATED_SCENES: SceneryOption[] = (() => {
  const map = new Map<string, SceneryOption>();
  // First add all uploaded and sacred ceremony scenes
  ALL_UPLOADED_AND_SACRED_SCENES.forEach((opt) => {
    map.set(opt.imageUrl, opt);
  });
  // Then add all theme scenery options
  Object.values(INDIAN_STATE_THEMES).forEach((theme) => {
    theme.sceneryOptions.forEach((opt) => {
      if (!map.has(opt.imageUrl)) {
        map.set(opt.imageUrl, { ...opt, themeName: theme.stateLabel });
      }
    });
  });
  return Array.from(map.values());
})();

// Sample bride & groom photos for instant testing
export const SAMPLE_BRIDE_PHOTO = 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80';
export const SAMPLE_GROOM_PHOTO = 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80';
